# Generated by Django 4.0.5 on 2022-06-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the project's languages", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description about the project', max_length=1000)),
                ('languages', models.ManyToManyField(help_text='Select a language', to='projects.languages')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.owner')),
            ],
        ),
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(help_text='Enter a technology, framework, library... (e.g. React)', max_length=200),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='project',
            name='tecnologies',
            field=models.ManyToManyField(help_text='Select a technology.', to='projects.technologies'),
        ),
    ]
