# Generated by Django 4.0.5 on 2022-06-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_languages_project_alter_technologies_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tecnologies',
            new_name='technologies',
        ),
    ]
