# Generated by Django 4.0.5 on 2022-06-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_tecnologies_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='nickname',
        ),
    ]
