# Generated by Django 4.0.5 on 2022-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_owner_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='nickname',
            field=models.CharField(default='fanstasma', max_length=50),
            preserve_default=False,
        ),
    ]
