# Generated by Django 4.0.5 on 2022-06-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_owner_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
