# Generated by Django 4.0.5 on 2022-06-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_languages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languages',
            options={},
        ),
    ]
